### ISSUE TITLE
Increase visibility to resources stuck in a terminating state

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware-tanzu/octant#1408]
**Describe the problem/challenge you have**
xref: https://github.com/kubernetes/kubernetes/issues/60807

Cases where resources can be stuck in a terminating state:
 - an object being deleted has a finalizer
 - a namespace being deleted contains a finalizer
 - a namespace being part of an APIService (example with cert-manager https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-524772920)

**Describe the solution you'd like**
Users of Kubernetes who are unaware of this issue would have to find the relevant Github issue to fix this. Octant can provide value by suggesting cleanup of orphaned apiservices or an interface to patch over an unused finalizer.

**Environment:**

- Octant version (use `octant version`): 0.16
- Kubernetes version (use `kubectl version`): 1.18.2
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): ubuntu

**Comment by scothis** [comment]
How do you distinguish "stuck" resources vs resources that are gracefully cleaning up external state before being fully deleted?

**Comment by GuessWhoSamFoo** [comment]
For namespaces specifically, we can highlight the condition (https://github.com/kubernetes/kubernetes/pull/82189).

Octant doesn't have to distinguish the graceful case. It can show a warning to the effect of "if this resources is not terminating like you'd expect, consider looking at relevant finalizer/apiserver/controller". Maybe these is a way to be more specific

**Comment by wwitzel3** [comment]
Example of a terminating namespace status

```
status:
  conditions:
  - lastTransitionTime: "2021-07-14T18:19:44Z"
    message: 'Discovery failed for some groups, 1 failing: unable to retrieve the
      complete list of server APIs: admission.certmanager.k8s.io/v1beta1: the server
      is currently unable to handle the request'
    reason: DiscoveryFailed
    status: "True"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2021-07-14T18:19:44Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2021-07-14T18:19:44Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2021-07-14T18:19:44Z"
    message: All content successfully removed
    reason: ContentRemoved
    status: "False"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2021-07-14T18:19:44Z"
    message: All content-preserving finalizers finished
    reason: ContentHasNoFinalizers
    status: "False"
    type: NamespaceFinalizersRemaining
  phase: Terminating
```
