### ISSUE TITLE
Show pod status in Workloads / Pods view

### ISSUE THREAD

**Issue by alexbrand** [vmware-tanzu/octant#201]
Kubectl seems to do some magic to show a "STATUS" of a given pod:

```
NAME                       READY   STATUS              RESTARTS   AGE
busybox-644dbf5f4b-2sjfs   1/1     Terminating         0          42m
busybox-644dbf5f4b-l5lzn   0/1     ContainerCreating   0          31m
```

I was somewhat surprised when I used Octant to look at the same set of pods. This is what Octant shows:

![image](https://user-images.githubusercontent.com/545723/63448906-fd4f6000-c40c-11e9-9954-c75e39c5c342.png)

Notice how kubectl says the first pod is `Terminating` and the second is `ContainerCreating`, whereas Octant shows `Running` and `Pending`.

I understand that Octant is showing the pod's `Phase` and not the `Status` (I am actually not sure how kubectl computes this), but it was super confusing at first.

I am wondering if we should follow kubectl here and show `Status` instead of `Phase`, or perhaps add a new column that shows `Status`.

**Comment by wwitzel3** [comment]
We are planning to refactor the way we do object status and this will be addressed at that time. Though it still may not map exactly to what you see in kubectl output, it will be improved to provide a better level of detail over just pending / running.

**Comment by wwitzel3** [comment]
Both status and phase should be displayed in Octant.

```
  containerStatuses:
  - image: quay.io/covalent/demo-elasticsearch:v1.2
    imageID: ""
    lastState: {}
    name: elasticsearch
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "quay.io/covalent/demo-elasticsearch:v1.2"
        reason: ImagePullBackOff
  hostIP: 10.128.15.203
  phase: Pending
  podIP: 10.48.7.15
  podIPs:
  - ip: 10.48.7.15
  qosClass: BestEffort
  startTime: "2021-07-14T17:49:16Z"
```
