### ISSUE TITLE
Expression filters are not rendered correctly

### ISSUE THREAD

**Issue by xtreme-jon-ji** [vmware-tanzu/octant#2252]
**What steps did you take and what happened:**
1. Apply a deployment that contains a `matchExpressions` selector. Example:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      labelA: someLabelA
    matchExpressions:
      - key: labelB
        operator: In
        values:
          - someLabelB
  template:
    metadata:
      labels:
        labelA: someLabelA
        labelB: someLabelB
    spec:
      containers:
        - image: nginx
          name: nginx
```
2. Navigate to `Namespace Overview`, or any screen where deployments are listed
3. See values in the `Selector` column - they appear as: `labelA:someLabelA` and `labelB:`

<img width="1243" alt="Screenshot 2021-03-31 at 2 42 10 PM" src="https://user-images.githubusercontent.com/4840235/113101516-6628cc00-922f-11eb-8641-4c42cd84b4c8.png">

**What did you expect to happen:**
1. The expression selector should be rendered as: `labelB In someLabelB`

**Anything else you would like to add:**
It looks like the `selectors` type is being rendered as an `OverflowSelectorsComponent`, which is treating each selector as a label selector.

**Environment:**
Octant version: 0.18.0
