### ISSUE TITLE
Port Forward seems to be broken

### ISSUE THREAD

**Issue by jgkirschbaum** [vmware-tanzu/octant#2279]
Deploying the example
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
        type: webapp
    spec:
      containers:
      - name: webapp
        image: docker.io/hashicorp/http-echo:latest
        ports:
        - containerPort: 11001
        args:
        - "-text=Hello openKV"
        - "-listen=:11001"
```
on my k8s cluster works as expected ;-) Doing a port forward on the pod produces the following error message in the octant console

```
2021-04-07T14:00:58.135+0200    ERROR   action/manager.go:193   actionFunc returned err: create port forwarder: creating forwarder: portforward terminated due to parent context: 6eaf06dd-ea59-40a1-a453-51e72877de1e  {"component": "action-manager"}
github.com/vmware-tanzu/octant/pkg/action.(*Manager).Dispatch
        /__w/octant/octant/pkg/action/manager.go:193
github.com/vmware-tanzu/octant/internal/api.(*WebsocketState).Dispatch
        /__w/octant/octant/internal/api/websocket_state.go:187
github.com/vmware-tanzu/octant/internal/api.(*ActionRequestManager).PerformAction
        /__w/octant/octant/internal/api/action_request_manager.go:55
github.com/vmware-tanzu/octant/internal/api.(*WebsocketClient).handle.func1
        /__w/octant/octant/internal/api/websocket_client.go:191
golang.org/x/sync/errgroup.(*Group).Go.func1
        /__w/octant/octant/vendor/golang.org/x/sync/errgroup/errgroup.go:57
W0407 14:01:05.606538   10592 reflector.go:424] /__w/octant/octant/internal/objectstore/dynamic_cache.go:389: watch of *unstructured.Unstructured ended with: an
 error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
```

I would expect that the port of the pod is forwarded. Works with ocatant `0.16.3`. Error first seen in octant `0.17.0`.

**Environment:**

- Octant version (use `octant version`):
```
Version:  0.18.0
Git commit:  044ec34141f9cac3735a9ea4ce7575d632e1938b
Built:  2021-03-25T22:29:34Z
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
```
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
```
Windows 7 SP1
```
