### ISSUE TITLE
Regression when opening namespace with Ingress resources

### ISSUE THREAD

**Issue by alk-automize** [vmware-tanzu/octant#2422]
**What steps did you take and what happened:**
Open a namespace with the dropdown selector and the resources are never displayed, only a spinning circle. The namespace contains multiple Ingress ressources.

_From the logs_
```
/private/tmp/octant-20210413-6707-1dwmad3/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:132
2021-05-04T09:51:07.324+0200	ERROR	api/content_manager.go:158	generate content	{"client-id": "<redacted>", "err": "generate content: scheme convert: converting (v1beta1.Ingress) to (v1.Ingress): unknown conversion", "content-path": "overview/namespace/<redacted>"}
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1
	/private/tmp/octant-20210413-6707-1dwmad3/src/github.com/vmware-tanzu/octant/internal/api/content_manager.go:158
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1
	/private/tmp/octant-20210413-6707-1dwmad3/src/github.com/vmware-tanzu/octant/internal/api/poller.go:86
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run
	/private/tmp/octant-20210413-6707-1dwmad3/src/github.com/vmware-tanzu/octant/internal/api/poller.go:95
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).Start
```

_Example Ingress yaml_
```
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: <servicename>
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: <servicehost>-<namespace>.domain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: <servicename>
              servicePort: <port>
```

Kubernetes version 1.18 has apiVersion networking.k8s.io/v1beta1 for Kind Ingress.
https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#ingress-v1beta1-networking-k8s-io

**What did you expect to happen:**
Namespace resources are displayed

**Anything else you would like to add:**
Working fine in Octant 0.17.0. Not working in 0.18.0 and up

**Environment:**

- Octant version (use `octant version`): 0.19.0
- Kubernetes version (use `kubectl version`): 1.18.8
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 11.3
