### ISSUE TITLE
Octant crashes when clicking a partially-runnning Pod from Applications view

### ISSUE THREAD

**Issue by davidmirror-ops** [vmware-tanzu/octant#2650]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
When browsing the Applications view and clicking into a 2-container Pod which has one of the containers in Error state, Octant crashes and throws this error:

W0714 11:44:41.926957   17597 reflector.go:424] github.com/vmware-tanzu/octant/internal/objectstore/dynamic_cache.go:389: watch of *unstructured.Unstructured ended with: an error on the server ("unable to decode an event from the watch stream: unable to decode to metav1.Event") has prevented the request from succeeding
panic: runtime error: index out of range [0] with length 0

**What did you expect to happen:**
Resource Viewer should open up

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

When i browse to that workload but from the Namespace Overview, Resource Viewer loads just fine

**Environment:**

- Octant version (use `octant version`): 0.21
- Kubernetes version (use `kubectl version`): 1.21
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): MacOS 11.4

**Comment by wwitzel3** [comment]
@davidmirror-ops can you share the deployment / yaml for the workload that is crashing. also the way you produced the state, this will greatly help with replication and debugging

**Comment by davidmirror-ops** [comment]
Sure @wwitzel3 

The whole environment can be easily reproduced:

https://github.com/wuestkamp/cka-example-environments

You just need Vagrant+Virtualbox installed

Once deployed, going to the "web-server" Pod in the "management" namespace from the Applications view would reproduce the crash.

Nevertheless, YAML for the failing pod is here:

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-server
  name: web-server
  namespace: management
spec:
  containers:
  - image: nginx:1.16.1-alpine
    name: nginx
  - image: httpd:2.4.41-alpine
    name: httpd
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
```

Thanks
