### ISSUE TITLE
Apply YAML fails to convert payload

### ISSUE THREAD

**Issue by davidmirror-ops** [vmware-tanzu/octant#2835]
**What steps did you take and what happened:**

While trying to create a Persistent Volume from the "Apply YAML" section on Octant (both in the Electron and browser) it doesn't do anything.

The YAML for the resource:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flash-pv
  labels:
    type: local
    app: web
spec:
  storageClassName: flash
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```

Watching the logs, Octant reports the following:
```
ERROR	action/manager.go:193	actionFunc returned err: convert payload to apply yaml request: namespace is blank	{"component": "action-manager"}
```
But the Persistent Volume is not a namespaced resource, and applying the same YAML from kubectl works just fine
**What did you expect to happen:**

PV should be created from the Apply YAML view

**Anything else you would like to add:**
N/A

**Environment:**

- Octant version (use `octant version`): 0.23
- Kubernetes version (use `kubectl version`): 1.21
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 11.5.1
