### ISSUE TITLE
Troubles if octant launched behind reverse-proxy (nginx)

### ISSUE THREAD

**Issue by strangeman** [vmware-tanzu/octant#365]
We trying to share one octant installation across the team. But, if octant launched behind nginx, it not works and shows a white screen instead of the main area (namespace selector and left menu shows correctly).

![2019-10-24-184549_1917x880_scrot](https://user-images.githubusercontent.com/1083576/67468988-d3295100-f68e-11e9-9021-b1f4e23cf31a.png)

Nginx config:
```
    location / {
        proxy_pass http://localhost:7777;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_request_buffering off;
        proxy_buffering off;
    }


    location /api/v1/stream {
      proxy_pass http://localhost:7777;
      proxy_http_version 1.1;
      proxy_set_header Upgrade "websocket"; #prevent error websocket: the client is not using the websocket protocol: 'websocket' token not found in 'Upgrade'
      proxy_set_header Connection "keep-alive, Upgrade";
      proxy_set_header Origin "";
      proxy_request_buffering off;
      proxy_buffering off;
    }
```

If I go to http://localhost:7777 - all work correctly.

In logs I see this:
```
2019-10-24T08:53:31.186Z        DEBUG   api/content_manager.go:117      generating content      {"client-id": "78159ed4-f63b-11e9-9509-0242ac1b0002", "contentPath": "overview/namespace/default/workloads/pods/XXXXXX", "elapsed": "1.914502146s"}
```

Octant 0.8.0, Nginx 1.13.7

**Comment by wwitzel3** [comment]
We have some environment variables that can be set to aid in getting Octant to work when being viewed from a location other than localhost, https://github.com/vmware-tanzu/octant/blob/master/docs/getting-started.md#environment-variables

You can get the listener address to all hosts, like 0.0.0.0 or you can add explicit allowed hosts.

**Comment by strangeman** [comment]
Got 404 for this link and can't see the `docs` folder in the repo.

**Comment by a-savinov** [comment]
can you show your nginx config 

> 
> 
> We have some environment variables that can be set to aid in getting Octant to work when being viewed from a location other than localhost, https://github.com/vmware-tanzu/octant/blob/master/docs/getting-started.md#environment-variables
> 
> You can get the listener address to all hosts, like 0.0.0.0 or you can add explicit allowed hosts.

can you show your nginx config ?

**Comment by a-savinov** [comment]
> 
> 
> Got 404 for this link and can't see the `docs` folder in the repo.

right url https://github.com/vmware-tanzu/octant/blob/master/site/docs/master/getting-started.md

**Comment by wwitzel3** [comment]
@strangeman any luck getting things working with those environment variables?

**Comment by strangeman** [comment]
No luck yet. Looks like something wrong with websockets, because all other
static and dynamic content (like list of namespaces) works well.

**Comment by strangeman** [comment]
We figured out this issue, had a problem with Nginx.

**Comment by maxisam** [comment]
@strangeman do you figure it out? I have the same issue. Somehow websocket doesn't work .

**Comment by strangeman** [comment]
@maxisam yeah, we just put "magic websocket settings for nginx" to the root location instead of `/api/v1/stream`

**Comment by sriharshakx** [comment]
> @strangeman do you figure it out? I have the same issue. Somehow websocket doesn't work .
> 
> /api/v1/stream' failed: Error during WebSocket handshake: Unexpected response code: 403
> 
> --solved by adding the following config.
> 
> ```
>   proxy_set_header Upgrade "websocket";
>   proxy_set_header Connection "keep-alive, Upgrade";
>   proxy_set_header Origin "";
>   proxy_request_buffering off;
>   proxy_buffering off;
> ```

You saved my day. Thanks

**Comment by ysaakpr** [comment]
Anyone able to get this working through nginx-ingress ?
2020-09-12T06:24:57.395Z	ERROR	api/websocket_service.go:43	create websocket client	{"err": "websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}
github.com/vmware-tanzu/octant/internal/api.serveWebsocket
	/__w/octant/octant/internal/api/websocket_service.go:43
github.com/vmware-tanzu/octant/internal/api.websocketService.func1
	/__w/octant/octant/internal/api/websocket_service.go:35
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2012
github.com/vmware-tanzu/octant/internal/api.rebindHandler.func1.1
	/__w/octant/octant/internal/api/middleware.go:121
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2012
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210
github.com/vmware-tanzu/octant/pkg/octant.noCacheRootMiddleware.func1
	/__w/octant/octant/pkg/octant/options.go:85
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2012
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210
github.com/gorilla/handlers.(*cors).ServeHTTP
	/go/pkg/mod/github.com/gorilla/handlers@v1.4.2/cors.go:138
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2807
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1895
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x17a1c62]

goroutine 208 [running]:
github.com/vmware-tanzu/octant/internal/api.(*WebsocketClient).readPump.func1(0x0)
	/__w/octant/octant/internal/api/websocket_client.go:128 +0x22
panic(0x1a9c8a0, 0x45f3360)
	/usr/local/go/src/runtime/panic.go:967 +0x15d
github.com/vmware-tanzu/octant/internal/api.(*WebsocketClient).readPump(0x0)
	/__w/octant/octant/internal/api/websocket_client.go:140 +0x7f
created by github.com/vmware-tanzu/octant/internal/api.serveWebsocket
	/__w/octant/octant/internal/api/websocket_service.go:47 +0xac

**Comment by ysaakpr** [comment]
```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: octant
  namespace: octant
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
spec:
  rules:
    - host: octant.livspace.com
      http:
        paths:
          - path: /
            backend:
              serviceName: octant-svc
              servicePort: 3309
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: octant-stream
  namespace: octant
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.org/websocket-services: octant-svc
spec:
  rules:
    - host: octant.livspace.com
      http:
        paths:
          - path: /api/v1/stream
            backend:
              serviceName: octant-svc
              servicePort: 3309
```
