### ISSUE TITLE
Port forwarder fails : portforward terminated 

### ISSUE THREAD

**Issue by nitinnbisht** [vmware-tanzu/octant#391]
# What
Port forwarder fails 
# When
Port forwarded works fine with pods exposing single port, but fails with an application with multiple ports. In my case it's the locust master ([docker image here](https://hub.docker.com/layers/greenbirdit/locust/0.9.0/images/sha256-e99d53bdc94403e653a468270b4125f4c8d56330f864dfcab8c8f5cb2e617cf7))
# Error Message
There is no error message in the application as it showing the animation for creating the port forwarder.
However, there is an error in the console section in the browser
```
received websocket unknown message of type handlerError with Object
parseWebsocketMessage @ main-es2015.f3cf8b8bca1b3debed1e.js:1
```

**Comment by GuessWhoSamFoo** [comment]
With the config below, I don't get terminated port forwards but a different bug where all the container ports attempt to forward from the UI. Are you able to share more information about your config?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    role: locust-master
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      role: locust-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: locust-master
    spec:
      containers:
      - image: greenbirdit/locust:0.9.0
        imagePullPolicy: IfNotPresent
        name: locust-master
        env:
          - name: ATTACKED_HOST
            valueFrom:
              configMapKeyRef:
                name: locust-cm
                key: ATTACKED_HOST
          - name: LOCUST_MODE
            value: MASTER
          - name: LOCUST_OPTS
            value: --print-stats
        volumeMounts:
          - mountPath: /locust
            name: locust-scripts
        ports:
        - containerPort: 5557
          name: comm
        - containerPort: 5558
          name: comm-plus-1
        - containerPort: 8089
          name: web-ui
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm
```
