### ISSUE TITLE
Octant not showing logs for pods running on Virtual Node

### ISSUE THREAD

**Issue by NileshGule** [vmware-tanzu/octant#649]
**What steps did you take and what happened:**
I am running a Kubernetes cluster on Azure Kubernetes Service (AKS) with Virtual Nodes enabled. The Kubernetes control plane of AKS shows the logs associated with pods which are scheduled on the physical nodes as well as the virtual nodes of the cluster. Octant is unable to show the logs for the same pods which are scheduled and running successfully on both physical as well as virtual nodes.

Please refer to the attached images for more details

**What did you expect to happen:**
My expectation is that under the logs section for each pod, Octant shows the logs correctly. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
Octant version : 0.9.1
Kubectl Client version 1.17.1
Kubectl server version : 1.14.8
OS : Windows 10

<img width="1144" alt="k8s virtual node logs" src="https://user-images.githubusercontent.com/1298374/74096037-73b75a00-4b34-11ea-8ca4-cb7eaf1bea80.PNG">
<img width="1909" alt="K8s virtual node pods" src="https://user-images.githubusercontent.com/1298374/74096038-7619b400-4b34-11ea-95ec-c346ed053bde.PNG">
<img width="893" alt="octant virtual node logs" src="https://user-images.githubusercontent.com/1298374/74096039-7619b400-4b34-11ea-952d-c43a65a9eec0.PNG">

- Octant version (use `octant version`): 
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Comment by wwitzel3** [comment]
I finally got an instance running on AKS with Virtual Nodes enabled and I'm going to start to look into this now.

**Comment by wwitzel3** [comment]
To allow Virtual Nodes to schedule properly, I had to register a provider:

`az provider register --namespace Microsoft.ContainerInstance`

To deploy to a virtual node, I added the following to my deployment spec:

```
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
```

Once I had done these, I was able to replicate the logging issue as well as find #707 and #708
