### ISSUE TITLE
Service of type ExternalName Error

### ISSUE THREAD

**Issue by kferrone** [vmware-tanzu/octant#797]
**What steps did you take and what happened:**
Deploy a service of type external name like so:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ExternalName
  externalName: host-to-external-mysql.com
```
The external host can be anything, I was just using mysql when issue came about. 

The issue is the External name type of services are not displayed and get the following error:
```
unable to print a nil object: failed to create item view: get endpoints for service mysql: endpoints "mysql" not found
```

It seems to care that the service does not have any endpoints, which it does not need because of type external name. 

**What did you expect to happen:**

I expect services of type ExternalName to be displayed just fine and Octane should know the endpoints on an ExternalName are optional. 

**Anything else you would like to add:**

There is a similar issue on the main k8s dashboard too. On k8s dashboard a service of type external name will always seem to be pending because the dashboard is waiting for its selector to select pods. However type ExternalName does not need to select pods and therefore . . . bug.

**Environment:**

- Octant version (use `octant version`):
```
Version:  0.11.0
Git commit:  20fbb90b767ff78983c034656e56b50d5ed1c5dd
Built:  2020-03-22T22:32:49Z
``` 
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
macOS Catalina 10.15.4 (19E266)
